### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by danielguerra69** [blacktop/docker-zeek#1]
Without the --branch @git clone, with the master, building goes well.
I think because of recent changes in zeek.

With your current version
I get this build error:
-- Could NOT find LibMMDB (missing: LibMMDB_LIBRARY LibMMDB_INCLUDE_DIR) 
-- Could NOT find LibKrb5 (missing: LibKrb5_LIBRARY LibKrb5_INCLUDE_DIR) 
-- Could NOT find GooglePerftools (missing: GooglePerftools_LIBRARIES GooglePerftools_LIBRARIES_DEBUG GooglePerftools_INCLUDE_DIR) 
-- Could NOT find tcmalloc (missing: GooglePerftools_LIBRARIES) 
CMake Error at CMakeLists.txt:199 (find_package):
  By not providing "FindFTS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FTS", but
  CMake did not find one.

  Could not find a package configuration file provided by "FTS" with any of
  the following names:

    FTSConfig.cmake
    fts-config.cmake

  Add the installation prefix of "FTS" to CMAKE_PREFIX_PATH or set "FTS_DIR"
  to a directory containing one of the above files.  If "FTS" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/tmp/zeek/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/zeek/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c echo "===> Compiling zeek..."   && cd /tmp/zeek   && CC=clang ./configure --prefix=/usr/local/bro   --disable-broker-tests   --disable-broctl   --disable-auxtools   && make   && make install' returned a non-zero code: 1

**Comment by blacktop** [comment]
I believe it is working now though it grew from 22MBs to 165MB ?! 😱 

Thank you for pointing that out to me 👍
