### ISSUE TITLE
problem running kafka zeek on macos Mojave

### ISSUE THREAD

**Issue by fwang49** [blacktop/docker-zeek#10]
Hi 

I tried to run zeek/kafka  integration on on macos Mojave.  

When I run  docker run --rm -v `pwd`:/pcap  -v `pwd`/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek --link kafka:localhost blacktop/zeek:kafka -P -r  heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }",

I got the following error:

warning in /usr/local/zeek/lib/zeek/plugins/APACHE_KAFKA/scripts/Apache/Kafka/./logs-to-kafka.zeek, line 39: deprecated (bro_init): Remove in v3.1: use zeek_init
fatal error in <params>, line 1: can't update DNS cache

I cannot figure out why. Can sombebody  help?

thanks

Frank
![Screen Shot 2020-02-02 at 4 51 28 AM](https://user-images.githubusercontent.com/6878249/73606384-b77bf380-4577-11ea-9ddb-e513bdf6b55a.png)

**Comment by blacktop** [comment]
I am trying to build it now with the latest zeek 3.1.1 and it is failing.  I have pinged the zeek-kafka plugin authors asking for help.

**Comment by blacktop** [comment]
So it's working for me now, not sure if the zeek-kafka people fixed it or the zeek people.  Please re-open the issue if it is not resolved
