### ISSUE TITLE
Error running the Zeek container

### ISSUE THREAD

**Issue by 0xh1n0k1** [blacktop/docker-zeek#11]
Hi,

I encountered the following error when running the docker-zeek for elastic using docker-compose.elastic.yml

WARNING: Image for service zeek was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
docker-zeek_elasticsearch_1 is up-to-date
docker-zeek_kibana_1 is up-to-date
docker-zeek_filebeat_1 is up-to-date
Creating docker-zeek_zeek_1 ... done
Attaching to docker-zeek_zeek_1
zeek_1           | Error relocating /usr/local/zeek/lib/libbroker.so.2: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/lib/libbroker.so.2: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/lib/libcaf_core.so.0.17.4: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/lib/libcaf_io.so.0.17.4: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/lib/libcaf_openssl.so.0.17.4: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/bin/zeek: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
zeek_1           | Error relocating /usr/local/zeek/bin/zeek: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
docker-zeek_zeek_1 exited with code 127

Please advise. Thank you.

**Comment by blacktop** [comment]
I have pushed up a "fix" where I don't strip the binary anymore for the elastic build of zeek, can you try again with the latest image once it's done building in dockerhub please?

**Comment by blacktop** [comment]
I needed to fix the filebeat image and I also updated the docker-compose to use the latest 7.7.1 versions of Elasticsearch etc.  Hope this helps, please re-open if it does not.
