### ISSUE TITLE
Path for .zeek files described in the documentation is not loaded by Zeek

### ISSUE THREAD

**Issue by masual** [blacktop/docker-zeek#12]
Hi!

I was trying to load a custom `local.zeek` config script by mounting it at `/usr/local/share/zeek/site/local.zeek` as described in[ the documentation.](https://github.com/blacktop/docker-zeek/blob/master/docs/usage.md) The changes introduced by the script were not working, so I checked the zeek logs and observed that the `local.zeek` file being loaded was located at `/usr/local`**`/zeek/`**`share/zeek/site/local.zeek`. After mounting my `local.zeek` file at this location, Zeek loaded it and the changes were applied.

**Comment by blacktop** [comment]
This is my favorite issue so far as it was accompanied by a PR fixing the issue ❤️
