### ISSUE TITLE
January 11, 2022 Final brownout

### ISSUE THREAD

**Issue by Ghost911-s** [blacktop/docker-zeek#25]
Because of the Final brownout the git address in line 56 needs to be corrected to https://github.com/hosom/file-extraction

**Comment by blacktop** [comment]
what is the "Final brownout" ?

**Comment by Ghost911-s** [comment]
GitHub tries to make it a bit more secure and isn´t accepting git: anymore.
https://thechief.io/c/news/github-is-making-protocol-security-changes-for-ssh-users/
