### ISSUE TITLE
Enabling the broctl fails the build

### ISSUE THREAD

**Issue by lbpan** [blacktop/docker-zeek#3]
I am trying to build this docker image by removing the --disalbe-broctl option in configure because I want the broctl functionality in my container. 
I am getting the following error: 
================================================================

-- Found SubnetTree: build from source aux/pysubnettree  
CMake Error at aux/broctl/cmake/InstallShellScript.cmake:44 (message):
  Absolute path to interpreter 'bash' not found, failed to configure shell
  script: /tmp/zeek/aux/broctl/bin/archive-log
Call Stack (most recent call first):
  aux/broctl/CMakeLists.txt:88 (InstallShellScript)

Please let me know how to build the docker image with broctl

**Comment by blacktop** [comment]
seems like you need to add `bash` to the apk add --no-cache` line, Alpine by default only ships with `/bin/sh` to keep it as small as possible.

**Comment by blacktop** [comment]
please let me know if you get it working, I don't use broctl, but have always wanted to allow for clustered deployments

**Comment by lbpan** [comment]
Thanks for the quick response. I was able to build the image by adding bash. But I am not able to run broctl. The shell says "command not found" even though the executable is in the bin directory. I am running from the bin directory and did chmod for broctl.   Btw, I could run docker exec /bin/sh in the container, but not /bin/bash.

**Comment by lbpan** [comment]
I got the broctl to run (with bro 2.5). I had to install python inside the container. The logs are being generated and captured, but broctl reports the status as crashed. The same thing happened with another docker bro image based on Alpine. Is it an Alpine issue?

**Comment by blacktop** [comment]
Have you seen it work on a ubuntu based docker image?

**Comment by blacktop** [comment]
Can you give me more info on how you are running it? Are you trying it as a cluster? Or just as a single node?

**Comment by lbpan** [comment]
I am running as a single node. I am running the image as follows:
docker run -d --net=host blacktop/docker-bro -i ens33 -C
docker exec -it <imageid>  /bin/bash
I ran broctl from bash in the container. The status shows as crashed. 
The same thing happened with dpisano/docker-bro which is also alpine based. Broctl reports status as crashed, but the logs are being generated and the bro process is running. 
However, broctl reports correctly on the image I built based on Ubuntu. But the size of the image I built is unwieldly big. Trying to optimize that size.

**Comment by blacktop** [comment]
Did you ever figure this out?

**Comment by blacktop** [comment]
Also can you try again with this image because I know the Zeek team has been making a LOT of updates to master

**Comment by blacktop** [comment]
I think this is because I compile WITHOUT broctl by default `  --disable-broctl \`

**Comment by blacktop** [comment]
I am adding a 🆕 flavor called `broctl` that should do what you want.
