### ISSUE TITLE
Monitoring specific port 

### ISSUE THREAD

**Issue by arun81** [blacktop/docker-zeek#5]
Hi 
Thanks for this Project for combining ELK with Zeek
Can you please explain for monitoring specfic ethernet port in docker-compose.elastic.yml file as you have given for pcap file 
Thanks you for the same

Thanks

**Comment by blacktop** [comment]
Please see https://github.com/blacktop/docker-zeek/blob/master/docs/elastic.md#use-live-traffic

**Comment by blacktop** [comment]
Also in the docker-compose file https://github.com/blacktop/docker-zeek/blob/master/docker-compose.live.yml
