### ISSUE TITLE
Zeek running at 300% cpu

### ISSUE THREAD

**Issue by gnomefish** [blacktop/docker-zeek#8]
Is it normal that the container runs at almost 300% cpu (see screenshot from portainer). running it with this command line:

docker run -d --name zeek --cap-add=NET_RAW --net=host -v /opt/threathunt/zeek/logs:/pcap:rw -v /opt/threathunt/zeek/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek blacktop/zeek -i ens33 local "Site::local_nets += { 172.16.100.0/24 }"

<img width="982" alt="Screenshot 2019-12-27 at 15 08 50" src="https://user-images.githubusercontent.com/7964766/71520163-010f5980-28bb-11ea-857b-0f0976680168.png">

Cheers,
Luk

**Comment by blacktop** [comment]
I am unsure what "normal" load looks like.  Maybe the Zeek devs would know?  I mostly use Zeek as a replacement for things like tshark, etc.  You could limit the CPU/MEM that zeek is allowed to use with the following flags:

```
--cpus 2 --memory 4g 
```
