### ISSUE TITLE
zeek 3.1 incompatible with kafka plugin

### ISSUE THREAD

**Issue by Nash-x9** [blacktop/docker-zeek#9]
I tried to Run Bro with the Kafka plugin,there is sth wrong tips:
warning in /usr/local/zeek/lib/zeek/plugins/APACHE_KAFKA/scripts/Apache/Kafka/./logs-to-kafka.zeek, line 39: deprecated (bro_init): Remove in v3.1: use zeek_init
fatal error in <params>, line 1: can't update DNS cache

**Comment by blacktop** [comment]
I bumped to 3.0.1 and built and ran my kafka tests: `kafka/tests/kafka.sh` and it seems to be working fine.  Can you try again with the new image ?

**Comment by fwang49** [comment]
I had the eaxct issue. Please see the screenshot.
![Screen Shot 2020-02-02 at 4 51 28 AM](https://user-images.githubusercontent.com/6878249/73615594-38b6a300-45d7-11ea-98d4-640e304dbdca.png)

**Comment by blacktop** [comment]
I am trying to build it now with the latest zeek 3.1.1 and it is failing.  I have pinged the zeek-kafka plugin authors asking for help.
